spring.application.name=music-player


spring.datasource.url=jdbc:mysql://localhost:3307/musicPlayer
spring.datasource.username=root
spring.datasource.password=FAfa05052006

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

server.port=8081